### ISSUE TITLE
fresh install, stuck

### ISSUE THREAD

**Issue by nagualcode** [Delapouite/louxor#1]
Hello, I running a fresh debian install.
after installing npm, nodejs and nodejs-legacy, 
I installed luxor via npm.
but an attempt to run results in:

`/usr/local/lib/node_modules/louxor/src/server/index.js:9
module.exports = ({ port, browser }) => {
                        ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/louxor/bin/louxor.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)`

**Comment by Delapouite** [comment]
Hi.
What is the debian version of node ?

```
node -v
```
